### PR TITLE
[Feature] Add Fun fact button

### PR DESCRIPTION
**Pull request by chimosky**
Added a fun fact button, that when clicked shows periodic table fun facts.

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl @cristian99garcia kindly review.

**Comment by quozl** [comment]
Reviewed;
* where did the fun facts come from, and under what copyright and license?
* does the dialog need to be modal?
* could an Alert or related Sugar Toolkit class be used?
* the code in `get_fact` is wasteful, a functional equivalent with same mathematical outcome is; `return random.choice(fact_list)`,
* the same fun fact may appear again before other fun facts are seen; suggest you randomise them before adding to the source code, and show them in that fixed order and have a back and forward button on the dialog.
* to meet expectations of existing maintainers, the new SVG should be in an `icons` directory,
* in future for a new feature please squash your commits into one commit before making pull request, unless there is a good reason for multiple commits; while we can squash at point of merge, it makes review harder.

**Comment by chimosky** [comment]
> where did the fun facts come from, and under what copyright and license?

TBH i really can't remember the sources, my search history doesn't help

> does the dialog need to be modal?

Not really

> could an Alert or related Sugar Toolkit class be used?

I'll look for related Sugar Toolkit class, for Alert i think it defeats the intended look

> the code in get_fact is wasteful, a functional equivalent with same mathematical outcome is; return random.choice(fact_list),

Thanks, I'll make the change

> the same fun fact may appear again before other fun facts are seen; suggest you randomise them before adding to the source code, and show them in that fixed order and have a back and forward button on the dialog.

The chances of the same fun fact appearing again are very slim as in `fun_facts.py` the list is shuffled twice - one before a fact is selected and one after -, should the randomising be where it is at the moment - `fun_facts.py` - in essence you're saying i should randomise once and store so as to use?. And in each session the `fact_list` is randomised once and the back and forth shows previous and next facts?. 

> to meet expectations of existing maintainers, the new SVG should be in an icons directory,

Noted, thanks.

> in future for a new feature please squash your commits into one commit before making pull request, unless there is a good reason for multiple commits; while we can squash at point of merge, it makes review harder.

Noted, thanks.

**Comment by quozl** [comment]
> i really can't remember the sources, my search history doesn't help

You mean they were words copied from various web sites you had found?  That's a good start to say that.  They can be found again by Google Search with quotes around them.

For instance, [this search](https://www.google.com/search?client=ubuntu&channel=fs&q=%22When+argon+was+discovered+in+1894%22&ie=utf-8&oe=utf-8) shows an instance of the phrase asserted to be owned by Tisha Anants, and covered by [Quora license terms](https://www.quora.com/about/tos).  But it could be derived from Oliver Sacks' book [Uncle Tungsten](https://books.google.com.au/books?id=y-XJyjWlmm0C&pg=PT209&lpg=PT209&dq=%22When+argon+was+discovered+in+1894%22&source=bl&ots=8ESSlcweTf&sig=vm4Tgnyk5mQ6203316AHtlpR1ZU&hl=en&sa=X&ved=0ahUKEwjb3sPA34jcAhVEv7wKHXE2DFMQ6AEIRzAE#v=onepage&q=%22When%20argon%20was%20discovered%20in%201894%22&f=false), ISBN 1743290101, 9781743290101.  That's very much in copyright, and I wouldn't want to tread on Oliver's rights, so you might instead use his original wording with attribution.  His other books are well known.

> Alert i think it defeats the intended look

Perhaps, but there are several variants on Alert in the classes, and they can induce proper resizing of the canvas when they are shown.  Have a look at the Save-As feature alerts in the toolkit, which include a text entry.  You can add forward and back buttons instead.

> The chances of the same fun fact appearing again are very slim as in `fun_facts.py` the list is shuffled twice - one before a fact is selected and one after -, should the randomising be where it is at the moment - `fun_facts.py` - in essence you're saying i should randomise once and store so as to use?. And in each session the `fact_list` is randomised once and the back and forth shows previous and next facts?. 

In your code now, the chances of the same fun fact appearing again each time are exactly one in thirty five, or `P(same) = 0.029`.  The probability does not change with the shuffling, which is why I said the shuffling does nothing mathematically useful.

For the fun facts to be useful and welcome they should not repeat until they are exhausted.  Either;

* randomise once for insertion into the source code and store a playback index in the instance directory (so that every learner will see the same random order), or;
* randomise on first run when where is no state in the instance directory, and store the order and playback index in the instance directory (so that every learner will see a different random order).

The latter would generate more classroom interaction, so that's my favourite.

**Comment by rhl-bthr** [comment]
Stale, closing

**Pull request closed without merging**
