### PR TITLE
Add search bar 

### PR DESCRIPTION
**Pull request by kipply**
Also did some linting and updated a bit of the element info. 

Search bar searches automatically and sets non-matching elements to be grayed out. Searches only match from the front of the string ("li" will match "Lithium" but not "silicon"). Symbols can also be matched. Longer searches(5 characters) that are prone to misspelling allow for a 1 character difference in searching ("oganessen" will highlight "Oganesson" )

### CODE REVIEW

**Comment by cvgarciarea** [comment]
@kipply you actually did interesting things here!
But your code has an important problem: when I search an element (for example "gallium") it's displayed correctly, but once I move the mouse over other elements, they are displayed as they were search results too, here a screenshot (same if I set a temperature from the slider):
Screenshot

Another important point, I see you implemented an "automatic search" by spending a second without writing, it's pretty cool but it doesn't work for me.

An the last one, I think the search bar must be located after the two direction tool buttons (backward and forward buttons), like this screenshot:
Another screenshot

**Comment by kipply** [comment]
Fixed the toolbar positioning and disabled the non-highlighted blocks on hover. 

Still trying to figure out the auto search, really confused as to why it doesn't work (or how I broke it)

**Comment by cvgarciarea** [comment]
It works pretty fine right now! I only found the following problem:
When I clean the entry a bit quickly (I mean, using Ctrl+Del or clicking on "x" on the entry (see the screenshot)), the search results are not updated, it should show all elements as search results (because I don't searching anything).
Yes, another screenshot here

It's weird because when I clean the search entry pressing Del key repeatedly it works as it should.

**Comment by kipply** [comment]
I've just pushed a patch, and things seem to be going smoothly. Thanks for that catch!

**Comment by cvgarciarea** [comment]
It seems that it works now.

**Pull request merged**
